### ISSUE TITLE
How to run ? 

### ISSUE THREAD

**Issue by Kuppey** [AndreySeVeN/osuAutoBot#1]
Hello, i kinda like your programs and may i ask if how do you run this??? im kinda new in github and programming so i still dont know stuff...

**Comment by idMysteries** [comment]
Ez run. But i'm write it code for education. I'm use very bad c++ code without optimizations, classes (+-) and etc.

**Comment by LossyDragon** [comment]
@Kuppey  To run the game, you need to download this code, and have Microsoft Visual Studio (2015). Open the code and you should find a .sln file. Open it and press Build > Build Solution (Ctrl+Shift+B). 

Make sure you have the build set to Debug and x64. (Ignore the cast conversion warnings if shown from compile)

As to use the program for the game it's for. That would be up to you to figure out. A good way to know how to is to read the code and learn from it since you are new. int main() in main.cpp will give you a hand on how to follow the code as it will OpenSong() and then checkGame().
